version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"
    groups:
      production-npm:
        dependency-type: production
        update-types:
          - minor
          - patch
      development-npm:
        dependency-type: development
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "ci"
    groups:
      github-actions:
        patterns:
          - "*"
