approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

npmPreapprovedPackages:
  - "@springfield/*"

npmScopes:
  springfield:
    npmMinimalAgeGate: 0
    npmPublishRegistry: "https://registry.npmjs.org"
